version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: chatapp_db
      MYSQL_USER: chatapp
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    expose:
      - 3306
    restart: always
    volumes:
      - data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db: 
        condition: "service_healthy"

volumes:
  data: